### ISSUE TITLE
(!) all triples should be recorded using branded URLs

### ISSUE THREAD

**Issue by workergnome** [american-art/PUAM#30]
URIs without the data subdomain still exist in the triplestore. There are a bunch of MMOs with URIs like

http://americanartcollaborative.org/puam/object/10048

as well as 

http://data.americanartcollaborative.org/puam/object/10048

Are the un-prefixed ones typos, or are they legacy data?

**Comment by cathryng** [comment]
i thought the data/ prefix was done globally by ISI?  are these duping or did some just get missed?

**Comment by workergnome** [comment]
Not sure.  This isn't something in your data, @cathryng, but something that would happen in the mapping.  

I suspect that ether there's a typo somewhere in the mapping, where someone left of the` data.` prefix, *or* this was done early in the mapping process and just haven't been deleted.

**Comment by caknoblock** [comment]
The URI prefix is set for each data file and I think someone just set one or more of the prefixes wrong.  This is easily fixed.

**Comment by VladimirAlexiev** [comment]
There is also some data recorded against branded (pure) URLs like  http://data.crystalbridges.org/object/108.

I personally prefer this (and I think the museums should). But certainly having 3 varieties of URLs will make everyone's life unpleasant.

**Comment by workergnome** [comment]
@VladimirAlexiev: the branded URLs are intentional—art this point, Craig has them set up to redirect to the AAC endpoint, but this will allow migration to self-hosting once complete.

**Comment by VladimirAlexiev** [comment]
Yes, that's what I understood, and https://github.com/american-art/semantic-hosting/issues/4 describes how they can stay that way in the browser (rather than being AAC-ified) using Apache ModRewrite.

This issue is that semantic data is recorded against 3 varieties of URLs: all of it should be against branded URLs. I'll change the title

**Comment by workergnome** [comment]
One of the reasons that we're seeing this is because not all museums have set up the redirects already.  I'm not sure how that progress is happening—that's @caknoblock's domain, but I know that some institutions have already set up their redirects and can use the branded URLs, and some of them wanted more time, so are using the http://data.americanartcollaborative.org/puam/object/10048 urls until the redirects can be set up.  the http://americanartcollaborative.org/puam/object/10048 are typos or problems and should be fixed and deleted.

**Comment by VladimirAlexiev** [comment]
When you generate and store 10M triples, you better do it against stable URLs. 
IMHO the RDF conversion shouldn't depend on redirection details that change monthly.
http://data.artmuseum.princeton.edu doesn't resolve at present, but so what: you can still use this URL in the AAC repo, and the browse app will work.
When they get around to setting a redirect, that URL will lead to the AAC server.

**Comment by cathryng** [comment]
our redirect is now live - at the url mentioned above

**Comment by workergnome** [comment]
Great.  @caknoblock, flagging this for update once people are back.

**Comment by VladimirAlexiev** [comment]
The general issue is https://github.com/american-art/semantic-hosting/issues/4
