### ISSUE TITLE
(!) leave image URLs as they are in the source data

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/PUAM#36]
In contrast to #30, you should leave image URLs alone, because AAC hosts only data not images.
Eg http://data.americanartcollaborative.org/puam/object/38930 crm:P138i_has_representation	
http://data.americanartcollaborative.org/puam/artimage.princeton.edu/files/ProductionJpegs/INV11965.jpg but that URL is wrong.

The right URL is http://artimage.princeton.edu/files/ProductionJpegs/INV11965.jpg and shows some nice Indian men.

Put this object at [Object>Resources>Image mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_30-search_0) and check: it finds a URL, but displays a broken image.

**Comment by VladimirAlexiev** [comment]
Another extremely bad example is fom CCMA:
http://data.americanartcollaborative.org/ccma/object/4/httpembarkcolbyedu8080images2013003001cdjpg

Not only is the image URL prepended with AAC stuff, but all punctuation is removed, so there's no way to reconstruct the original.
- the webpage is http://embark.colby.edu/Obj4
- the image displayed on it is http://embark.colby.edu:8080/Previews/2013.003_001_cd.jpg
- So I thought the original is http://embark.colby.edu:8080/images/2013.003_001_cd.jpg but this returns 404 - File or directory not found: can someone say what is the correct one?
- Maybe Colby's DMS is broken. The ENLARGE/ZOOM IMAGE link goes to http://embark.colby.edu/academics_cs/museum/search/CUS.18.zoomobject.4?sid=190&x=88008&x=88009 which says File not found

**Comment by bsnikhila** [comment]
Image URIs in PUAM have been fixed.

**Comment by workergnome** [comment]
@bsnikhila, I'm not sure that they have.  For instance, http://data.americanartcollaborative.org/page/puam/object/10012 has image http://artimage.princeton.edu/files/ProductionJpegs/x1961_60_aa2.jpg, but that does not resolve.


(It may be that I chose a really bad example here—their website also seems to have the same issue.)

**Comment by workergnome** [comment]
OK.  I'm going to mark this fixed, with a note to @cathryng that there appears to be a problem with the image for object \#10012 in the source data.
